version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cafe-network

  api-gateway:
    build: ./Cafe_Management_System/api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - menu-service
      - order-service
      - payment-service
      - inventory-service
      - customer-service
    networks:
      - cafe-network

  menu-service:
    build: ./Cafe_Management_System/menu-services
    container_name: menu-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - cafe-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cafe

  order-service:
    build: ./Cafe_Management_System/order-services
    container_name: order-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
      - menu-service
      - customer-service
      - inventory-service
    networks:
      - cafe-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cafe

  payment-service:
    build: ./Cafe_Management_System/payment-services
    container_name: payment-service
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
      - order-service
    networks:
      - cafe-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cafe

  inventory-service:
    build: ./Cafe_Management_System/inventory-services
    container_name: inventory-service
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    networks:
      - cafe-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cafe

  customer-service:
    build: ./Cafe_Management_System/customer-services
    container_name: customer-service
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    networks:
      - cafe-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cafe

networks:
  cafe-network:
    driver: bridge

volumes:
  mongo-data: 