version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cafe-network
    restart: always

  api-gateway:
    image: ${DOCKERHUB_USERNAME}/cafe-api-gateway:latest
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - menu-service
      - order-service
      - payment-service
      - inventory-service
      - customer-service
    networks:
      - cafe-network
    restart: always

  menu-service:
    image: ${DOCKERHUB_USERNAME}/cafe-menu-services:latest
    container_name: menu-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - cafe-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cafe
    restart: always

  order-service:
    image: ${DOCKERHUB_USERNAME}/cafe-order-services:latest
    container_name: order-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
      - menu-service
      - customer-service
      - inventory-service
    networks:
      - cafe-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cafe
    restart: always

  payment-service:
    image: ${DOCKERHUB_USERNAME}/cafe-payment-services:latest
    container_name: payment-service
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
      - order-service
    networks:
      - cafe-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cafe
    restart: always

  inventory-service:
    image: ${DOCKERHUB_USERNAME}/cafe-inventory-services:latest
    container_name: inventory-service
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    networks:
      - cafe-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cafe
    restart: always

  customer-service:
    image: ${DOCKERHUB_USERNAME}/cafe-customer-services:latest
    container_name: customer-service
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    networks:
      - cafe-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cafe
    restart: always

networks:
  cafe-network:
    driver: bridge

volumes:
  mongo-data: 