name: Cafe Management System CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, menu-services, order-services, payment-services, inventory-services, customer-services]
        include:
          - service: api-gateway
            port: 3000
          - service: menu-services
            port: 3001
          - service: order-services
            port: 3002
          - service: payment-services
            port: 3003
          - service: inventory-services
            port: 3004
          - service: customer-services
            port: 3005

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./Cafe_Management_System/${{ matrix.service }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-${{ matrix.service }}:latest

  deploy:
    needs: build-and-push
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Create .env file
      run: |
        echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
        
    - name: Deploy to server
      run: |
        echo "Deploying to server..."
        # Add deployment logic here (e.g., SSH into server, pull images, run docker-compose)
        echo "Deployment completed!" 